# Generated by Django 3.2.5 on 2021-07-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210720_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro')], default='deposit', max_length=50, verbose_name='Opção de Pagamento'),
        ),
    ]
