# Generated by Django 3.2.5 on 2021-07-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20210712_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='detalhes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='estoque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editora_livro', to='livros.editora'),
        ),
    ]
