# Generated by Django 3.2.5 on 2021-07-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_auto_20210712_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='estoque',
        ),
    ]
