# Generated by Django 3.2.5 on 2021-07-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_remove_livro_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
