# Generated by Django 3.2.5 on 2021-07-14 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_livro_arquivo_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='arquivo_pdf',
        ),
        migrations.AddField(
            model_name='livro',
            name='estoque',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('desconto', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('categorias', models.ManyToManyField(to='livros.Categoria')),
            ],
        ),
    ]
