# Generated by Django 3.2.5 on 2021-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_auto_20210714_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocoes',
            name='ativo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
