# Generated by Django 3.2.5 on 2021-07-16 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_auto_20210716_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='desconto',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.DeleteModel(
            name='Promocao',
        ),
    ]
