# Generated by Django 3.2.5 on 2021-07-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_auto_20210716_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='estoque',
        ),
    ]
