# Generated by Django 3.2.5 on 2021-07-12 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.RemoveField(
            model_name='livro',
            name='encardenacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='encadernacao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Espiral'), (2, 'Canoa'), (3, 'Brochura'), (4, 'Wire-O'), (5, 'Lombada quadrada')], default=1, verbose_name='Encadernação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
    ]
