# Generated by Django 3.2.5 on 2021-07-16 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_rename_promocoes_promocao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
        migrations.RemoveField(
            model_name='editora',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias_promocao', to='livros.Categoria'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='desconto',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
